language: node_js
sudo: false
node_js:
- lts/dubnium
- node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: q4MSrR7XvRscDFloJfRfFiA0H3g66TD58dF3wVwtZUbK6mxD5x0c7DA/JOJu0Ph3MiFvTXytOqBh6vBi0NYozdm8VSzTrjARthDcrDY5PyaW5yZjOiOoFooCMeqHLI6BsrxulJ+//jQ8dc9IemWB+r80gdpqGDZxeLw5L4fGBgbet2AJMkuFMemQem9rrxID295Z7KxDH79i+cMzlbf3q4vdL5NMnXVRZPQybls7AFWUe6iJryWonImHfx5bOrdNMPyqe0Z3JPLaUV1kSvnqCoXn6amhVrSx8WPij++cSLwZS4kfg9r4h8MbI19Z6gaNKkGYvUgr8r1SjBQ7GqQxbK0le+7hM+gXvwioTBa7w2YN/WMMElPuckOTOuyjaJlhwDnX/a1PLYDtIDs2N2yYeDVqDZoYw8hUCeWQFeVPqYwb5LkfK2u/IYSAFiXMLmTKn8lpk+8rqD+fKTpXZs4B7tXSHqIXP5eXRX5CgRiTR4FHZUSmmE1Ag5nFVk0mw1Jiwms50JdtB/PrGtc6FVjNpCh+FeW77FeLj1E3xNggkhZQt6kzhZbFHJk836v7zQ/frT+HnnxyLh77hcDEKp3VPCveZvw962XVxqAAIOhoP4PJHGs6+eP+EqcStAh7WBjiwTwrkGfeOI4SsLhe/SSc/wbMvMTgDMDbGo1RGh1vu74=
  file:
    - 'afinn-165.js'
    - 'afinn-165.min.js'
  on:
    tags: true
